/**
 * Offline shelf-life lookup backed by the USDA FoodKeeper dataset.
 *
 * The bundled table (`assets/data/foodkeeper-shelf-life.json`, generated by
 * `scripts/build-foodkeeper.js`) holds 661 products with typical storage durations
 * in days. Receipt lines are messy ("ORG BANANAS 2LB", "MLK 2% GAL"), so matching is
 * fuzzy: we tokenise the item name and score each product by how many of its
 * FoodKeeper keywords appear in the name, with a small bonus for the product's
 * primary name and a Levenshtein-based fallback for single-token typos/abbreviations.
 */
import foodKeeperData from '../../../assets/data/foodkeeper-shelf-life.json';
import { APP_CONFIG } from '../../../config/env';

export type DayRange = [number, number];

export interface FoodKeeperProduct {
  id: number;
  name: string;
  subtitle: string | null;
  category: string | null;
  subcategory: string | null;
  keywords: string[];
  pantry: DayRange | null;
  fridge: DayRange | null;
  fridgeOpened: DayRange | null;
  freezer: DayRange | null;
}

export interface ShelfLifeEstimate {
  /** Recommended number of days from purchase until the item should be used. */
  days: number;
  /** Where the estimate assumes the item is stored. */
  storage: 'fridge' | 'pantry' | 'freezer' | 'default';
  /** The matched FoodKeeper product, or null when we fell back to a default. */
  product: FoodKeeperProduct | null;
  /** 0..1 confidence in the match (0 when no product matched). */
  confidence: number;
}

/** Typical days-until-use for a category when the matched product has no usable range. */
const CATEGORY_DEFAULT_DAYS: Record<string, number> = {
  'Dairy Products & Eggs': 7,
  Produce: 7,
  Meat: 3,
  Poultry: 2,
  Seafood: 2,
  'Deli & Prepared Foods': 4,
  'Baked Goods': 5,
  Beverages: 14,
  'Grains, Beans & Pasta': 180,
  'Shelf Stable Foods': 180,
  'Condiments, Sauces & Canned Goods': 90,
  'Vegetarian Proteins': 7,
  'Food Purchased Frozen': 90,
  'Baby Food': 3,
};

/** Common receipt abbreviations expanded before matching. */
const ABBREVIATIONS: Record<string, string> = {
  mlk: 'milk',
  chkn: 'chicken',
  chix: 'chicken',
  bnls: 'boneless',
  grnd: 'ground',
  gb: 'ground beef',
  org: 'organic',
  veg: 'vegetables',
  tmto: 'tomato',
  ptato: 'potato',
  strwbry: 'strawberries',
  yog: 'yogurt',
  chs: 'cheese',
  brd: 'bread',
  bttr: 'butter',
};

/** Tokens that appear on receipts but carry no information about the food itself. */
const STOP_WORDS = new Set([
  'the', 'and', 'of', 'with', 'organic', 'fresh', 'large', 'small', 'medium', 'pack', 'pk',
  'lb', 'lbs', 'oz', 'kg', 'g', 'ct', 'ea', 'each', 'gal', 'qt', 'pt', 'ml', 'l', 'x',
  'brand', 'value', 'great', 'kirkland', 'signature', 'select', 'choice', 'premium',
]);

const normalise = (text: string): string[] =>
  text
    .toLowerCase()
    .replace(/[^a-z\s-]/g, ' ')
    .split(/\s+/)
    .map((t) => ABBREVIATIONS[t] ?? t)
    .join(' ')
    .split(/\s+/)
    .filter((t) => t.length > 1 && !STOP_WORDS.has(t));

/** Crude singulariser so "bananas" matches the keyword "banana" and vice versa. */
const stem = (word: string): string => {
  if (word.endsWith('ies')) return word.slice(0, -3) + 'y';
  if (word.endsWith('es') && !word.endsWith('ses')) return word.slice(0, -2);
  if (word.endsWith('s') && !word.endsWith('ss')) return word.slice(0, -1);
  return word;
};

function levenshtein(a: string, b: string): number {
  const prev = Array.from({ length: b.length + 1 }, (_, i) => i);
  for (let i = 1; i <= a.length; i++) {
    let last = prev[0];
    prev[0] = i;
    for (let j = 1; j <= b.length; j++) {
      const tmp = prev[j];
      prev[j] = Math.min(prev[j] + 1, prev[j - 1] + 1, last + (a[i - 1] === b[j - 1] ? 0 : 1));
      last = tmp;
    }
  }
  return prev[b.length];
}

/** Similarity in 0..1 based on edit distance; tolerant of one-letter typos in short words. */
const similarity = (a: string, b: string): number => {
  if (a === b) return 1;
  const max = Math.max(a.length, b.length);
  return max === 0 ? 0 : 1 - levenshtein(a, b) / max;
};

interface PreparedProduct {
  product: FoodKeeperProduct;
  nameTokens: string[];
  keywordTokens: string[];
}

export class FoodKeeperService {
  private static instance: FoodKeeperService;
  private readonly products: PreparedProduct[];

  private constructor(products: FoodKeeperProduct[]) {
    this.products = products.map((product) => ({
      product,
      nameTokens: normalise(product.name).map(stem),
      keywordTokens: Array.from(
        new Set(product.keywords.flatMap((k) => normalise(k)).map(stem))
      ),
    }));
  }

  static getInstance(): FoodKeeperService {
    if (!FoodKeeperService.instance) {
      FoodKeeperService.instance = new FoodKeeperService(
        (foodKeeperData as { products: FoodKeeperProduct[] }).products
      );
    }
    return FoodKeeperService.instance;
  }

  /** Finds the FoodKeeper product that best matches a free-text item name. */
  findProduct(itemName: string): { product: FoodKeeperProduct; confidence: number } | null {
    const tokens = normalise(itemName).map(stem);
    if (tokens.length === 0) return null;

    let best: { product: FoodKeeperProduct; score: number } | null = null;

    for (const candidate of this.products) {
      let score = 0;
      for (const token of tokens) {
        // Exact keyword hit is worth 1; the product's own name counts a bit extra so that
        // "Chicken" beats "Chicken soup" for the input "chicken".
        if (candidate.keywordTokens.includes(token)) {
          score += candidate.nameTokens.includes(token) ? 1.25 : 1;
          continue;
        }
        // Fuzzy hit (typo / abbreviation) on the primary name only, to limit false positives.
        const fuzzy = Math.max(0, ...candidate.nameTokens.map((n) => similarity(token, n)));
        if (fuzzy >= 0.8) score += fuzzy * 0.75;
      }
      if (score === 0) continue;

      // Penalise long keyword lists slightly so generic entries don't dominate,
      // and prefer entries without a subtitle (the "plain" variant) on ties.
      score = score / Math.sqrt(candidate.nameTokens.length) - (candidate.product.subtitle ? 0.01 : 0);
      // Prefer products that can actually give us a duration.
      if (!this.usableRange(candidate.product)) score -= 0.05;

      if (!best || score > best.score) best = { product: candidate.product, score };
    }

    if (!best) return null;
    const confidence = Math.min(1, best.score / tokens.length);
    return confidence >= 0.35 ? { product: best.product, confidence } : null;
  }

  /**
   * Estimates how many days an item bought today will keep.
   * Prefers refrigerated storage (the common case for groceries), then pantry;
   * uses the upper bound of the range since the app warns 3 days before expiry anyway.
   */
  estimateShelfLife(itemName: string): ShelfLifeEstimate {
    const match = this.findProduct(itemName);
    if (!match) {
      return { days: APP_CONFIG.defaultExpiryDays, storage: 'default', product: null, confidence: 0 };
    }

    const { product, confidence } = match;
    const range = this.usableRange(product);
    if (range) {
      return { days: Math.max(1, range.days), storage: range.storage, product, confidence };
    }

    const categoryDays = (product.category && CATEGORY_DEFAULT_DAYS[product.category]) || APP_CONFIG.defaultExpiryDays;
    return { days: categoryDays, storage: 'default', product, confidence };
  }

  private usableRange(product: FoodKeeperProduct): { days: number; storage: 'fridge' | 'pantry' | 'freezer' } | null {
    if (product.fridge) return { days: product.fridge[1], storage: 'fridge' };
    if (product.fridgeOpened) return { days: product.fridgeOpened[1], storage: 'fridge' };
    if (product.pantry) return { days: product.pantry[1], storage: 'pantry' };
    if (product.category === 'Food Purchased Frozen' && product.freezer) {
      return { days: product.freezer[1], storage: 'freezer' };
    }
    return null;
  }
}

export const foodKeeperService = FoodKeeperService.getInstance();
export default FoodKeeperService;
